# Name of action
name: CI/CD to Vultr

on:
  push:
    branches: [production]

jobs:
  Setup:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

  Deploy-Site:
    runs-on: ubuntu-latest
    needs: Setup
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Deploying to Vultr
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.BR_PATH }}
            git pull
            cd ${{ secrets.ARENAS_PATH }}
            git pull
